version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: FluentValidation
    versions:
    - 9.3.0
    - 9.5.0
    - 9.5.1
  - dependency-name: ReactiveProperty
    versions:
    - 7.5.1
    - 7.7.0
  - dependency-name: Microsoft.VSSDK.BuildTools
    versions:
    - 16.8.3038
    - 16.9.1044
  - dependency-name: AWSSDK.S3
    versions:
    - 3.5.7.12
    - 3.5.7.4
