// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoSquirrel
{
    static class Vsix
    {
        public const string Id = "VS.Squirrel.Chris.Pulman.b619c884-a2aa-4750-8433-bdca671f6d26";
        public const string Name = "VS.Squirrel";
        public const string Description = @"Visual Studio Squirrel Packager - Create installer from Visual Studio and Deploy to a local file system or to Amazon S3 storage.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Chris Pulman";
        public const string Tags = "";
    }
}
