// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoSquirrel
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSquirrelPackagerPackageString = "0f423afa-e287-4ebc-b319-12bc988977f0";
        public const string guidSquirrelPackagerPackageCmdSetString = "a2e139eb-841b-414f-bcf2-b8745b7b7e4e";
        public const string guidImagesString = "3ae4334a-acca-4350-8f9c-23a31f93832b";
        public static Guid guidSquirrelPackagerPackage = new Guid(guidSquirrelPackagerPackageString);
        public static Guid guidSquirrelPackagerPackageCmdSet = new Guid(guidSquirrelPackagerPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SquirrelPackagerCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
